debug: false

logger.level:
  io.pivotal.dmfrey: DEBUG
  org.springframework.web: DEBUG
  com.netflix.feign: FULL
  org.springframework.cloud.openfeign: DEBUG

server:
  port: ${PORT:8765}
  use-forward-headers: true
  tomcat:
    remote-ip-header: x-forwarded-for
    protocol-header: x-forwarded-proto

ribbon.eager-load.enabled: true

spring:
  jackson:
    serialization:
      write_dates_as_timestamps: false
